theme: jekyll-theme-cayman
title: Homework 1
description: CMPM 163
README.md
Contains:
Part A: 3D Scene (code)
Part B: Image Processing (code)
Part C: Game of Life (code)
Part D: Visual Effect (document)
